# Generated by Django 3.1.6 on 2021-02-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
