# Generated by Django 3.1.6 on 2021-02-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_chosenproduct_sliderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='slider',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ChosenProduct',
        ),
        migrations.DeleteModel(
            name='SliderProduct',
        ),
    ]
